name = "OpenSWPC"
uuid = "8d4af537-8a72-42c0-afd5-633bf53a5533"
authors = ["Boris Kaus <kaus@uni-mainz.de>"]
version = "0.1.0"

[deps]
GeophysicalModelGenerator = "3700c31b-fa53-48a6-808a-ef22d5a84742"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
OpenSWPC_jll = "97e963f0-2dee-5a96-a601-8cee97e19b5a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
GeophysicalModelGenerator = "0.7.15"
Pkg = "1"
