name = "OpenSWPC"
uuid = "8d4af537-8a72-42c0-afd5-633bf53a5533"
authors = ["Boris Kaus <kaus@uni-mainz.de>"]
version = "0.1.0"

[deps]
GeophysicalModelGenerator = "3700c31b-fa53-48a6-808a-ef22d5a84742"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
NetCDF_jll = "7243133f-43d8-5620-bbf4-c2c921802cf3"
OpenSWPC_jll = "97e963f0-2dee-5a96-a601-8cee97e19b5a"
