name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} • ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, macos-15-intel, windows-latest]
        #os: [windows-latest]
        julia-version: ['1.10', '1.11','1.12']
    env:
      OPENSWPC_RUN_HEAVY: '1'
      JULIA_NUM_THREADS: '2'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v2
      - name: Instantiate
        run: |
          julia --color=yes --project=. -e 'using Pkg; Pkg.instantiate()'
      - name: Run tests
        run: |
          julia --color=yes --project=. -e 'using Pkg; Pkg.test(coverage=true)'

  nightly:
    name: Julia nightly • ubuntu
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      OPENSWPC_RUN_HEAVY: '0'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Debug workspace
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          pwd
          ls -la
          echo "List input_tests/test1:"
          ls -la input_tests/test1 || true
      - uses: julia-actions/setup-julia@v2
        with:
          version: 'nightly'
      - uses: julia-actions/cache@v2
      - name: Instantiate
        run: |
          julia --color=yes --project=. -e 'using Pkg; Pkg.instantiate()'
      - name: Run tests
        run: |
          julia --color=yes --project=. -e 'using Pkg; Pkg.test(coverage=true)'
